name: CI-CD http app

#Events
on: 
  push:
    branches:
      - main
      # - dev
      # - master

  # pull_request:
  #   branches:
  #     - main
  #     - dev

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
       #clone code on VM/runner
      - name: clone the code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.14.0

      # - name: Run test
      #   run: npm run test
      - name: install packages
        run: npm install
    #npm run build
      - name: build code
        run: npm run build

  