name: CI-CD http app

#Events
on: 
  push:
    branches:
      - main
      # - dev
      # - master

  # pull_request:
  #   branches:
  #     - main
  #     - dev

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
       #clone code on VM/runner
      - name: clone the code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.14.0

      # - name: Run test
      #   run: npm run test
      - name: install packages
        run: npm install
    #npm run build
      - name: build code
        run: npm run build

      - name: Upload atrifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: test_and_build
    
    steps:
      - name: clone the code
        uses: actions/checkout@v5

      - name: Download atrifact
        uses: actions/download-artifact@v4
        with: 
          name: dist
          path: dist/
          

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/ package.json"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd ${{ secrets.REMOTE_TARGET }}
            npm install
            cd ${{ secrets.REMOTE_TARGET }}/app
            pm2 restart app || pm2 start npm --name "app" -- start
    

  